apiVersion: v1
kind: Pod
metadata:
  name: mfcp-example-starter-sshfs
  namespace: default
spec:
  terminationGracePeriodSeconds: 10
  hostUsers: false
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    seccompProfile:
      type: RuntimeDefault
  containers:
  - name: starter
    image: ghcr.io/tak-55/meta-fuse-csi-plugin/mfcp-example-starter-sshfs:latest
    imagePullPolicy: Always
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      privileged: false
    volumeMounts:
    - name: fuse-fd-passing
      mountPath: /fuse-fd-passing
    - name: fuse-csi-ephemeral
      mountPath: /data
      readOnly: true
      mountPropagation: HostToContainer
    startupProbe:
      exec:
        command: ['sh', '-c', 'mount | grep /data | grep fuse']
      failureThreshold: 300
      periodSeconds: 1
  volumes:
  - name: fuse-fd-passing
    emptyDir: {}
  - name: fuse-csi-ephemeral
    csi:
      driver: meta-fuse-csi-plugin.csi.storage.pfn.io
      readOnly: true
      volumeAttributes:
        fdPassingEmptyDirName: fuse-fd-passing
        fdPassingSocketName: fuse-csi-ephemeral.sock
        mountOptions: volume-mount-group=1000
