apiVersion: v1
kind: Pod
metadata:
  name: mfcp-example-proxy-s3fs
  namespace: default
spec:
  terminationGracePeriodSeconds: 10
  hostUsers: false
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    seccompProfile:
      type: RuntimeDefault
  initContainers:
  - name: prepare-fuse-dev
    image: busybox
    command: ['sh', '-c', 'touch /fake-dev/fuse && chmod 0666 /fake-dev/fuse']
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      privileged: false
    volumeMounts:
    - name: fake-dev-fuse
      mountPath: /fake-dev
  - name: minio
    restartPolicy: Always
    image: quay.io/minio/minio:latest
    command: ["/bin/bash"]
    args: ["-c", "minio server /data --console-address :9090"]
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      privileged: false
    volumeMounts:
    - name: minio-data
      mountPath: /data
  containers:
  - name: starter
    image: ghcr.io/tak-55/meta-fuse-csi-plugin/mfcp-example-proxy-s3fs:latest
    imagePullPolicy: Always
    command: ["/bin/bash"]
    args: ["-c", "./configure_minio.sh && s3fs test-bucket /tmp -o url=http://localhost:9000 -o use_path_request_style -f"]
    env:
    - name: FUSERMOUNT3PROXY_FDPASSING_SOCKPATH
      value: "/fusermount3-proxy/fuse-csi-ephemeral.sock"
    - name: AWS_ACCESS_KEY_ID
      value: "minioadmin"
    - name: AWS_SECRET_ACCESS_KEY
      value: "minioadmin"
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      privileged: false
    volumeMounts:
    - name: fuse-fd-passing
      mountPath: /fusermount3-proxy
    - name: fake-dev-fuse
      mountPath: /dev/fuse
      subPath: fuse
    - name: fuse-csi-ephemeral
      mountPath: /data
      readOnly: true
      mountPropagation: HostToContainer
    startupProbe:
      exec:
        command: ['sh', '-c', 'mount | grep /data | grep fuse']
      failureThreshold: 300
      periodSeconds: 1
  volumes:
  - name: fuse-fd-passing
    emptyDir: {}
  - name: fake-dev-fuse
    emptyDir: {}
  - name: minio-data
    emptyDir: {}
  - name: fuse-csi-ephemeral
    csi:
      driver: meta-fuse-csi-plugin.csi.storage.pfn.io
      readOnly: true
      volumeAttributes:
        fdPassingEmptyDirName: fuse-fd-passing
        fdPassingSocketName: fuse-csi-ephemeral.sock
        mountOptions: volume-mount-group=1000
