apiVersion: v1
kind: Namespace
metadata:
  name: mfcp-system
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/warn: privileged
    pod-security.kubernetes.io/warn-version: latest
---
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    k8s-app: meta-fuse-csi-plugin
  name: meta-fuse-csi-plugin.csi.storage.pfn.io
spec:
  attachRequired: false
  fsGroupPolicy: File
  podInfoOnMount: true
  requiresRepublish: true
  storageCapacity: false
  volumeLifecycleModes:
  - Ephemeral
